---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-indexer
data:
  10-input-beat: |-
    input {
    beats {
      port => 5044
     }
    } 

  20-kubernetes-filter: |-
    filter  {
    if "log" == [input_type] {

    mutate {
     rename => ["source", "path"]
    }
    kube {
     add_tag => ["kubernetes_filtered"]
    }
    mutate {
     rename => ["path", "log_source"]
    }
    json {
     source => 'message'
     target => 'log'
      }
      date {
          match => [ "[log][time]", "ISO8601", "dd/MMM/YYYY:HH:mm:ss Z", "dd/MMM/YYYY/HH/mm/ss" ]
        }
     }
    }

  100-output-elasticsearch: |-
    output {
      elasticsearch {
        index => "logstash-k8s-%{+YYYY.MM.dd}"
        hosts => [{{elasticsearch_hosts}}]
        flush_size => 50
        }
     }
