---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: logstash
  name: logstash

spec:
  type: ClusterIP
  ports:
    - port: 5044
      targetPort: 5044
      name: logstash
  selector:
    k8s-app: logstash
